apiVersion: batch/v1
kind: Job
metadata:
  name: pinot-realtime-quickstart-load-data-into-kafka-${JOB_INDEX}
  namespace: pinot-quickstart
spec:
  template:
    spec:
      containers:
        - name: loading-json-data-to-kafka
          image: apachepinot/pinot:latest
          args: [ "StreamAvroIntoKafka", "-avroFile", "examples/stream/airlineStats/rawdata/airlineStats_data.avro", "-kafkaTopic", "flights-realtime", "-kafkaBrokerList", "kafka:9092", "-zkAddress", "kafka-zookeeper:2181", "-millisBetweenMessages", "1"]
      restartPolicy: OnFailure
  backoffLimit: 3

