
image:
  repository: apachepinot/pinot
  tag: 1.1.0

cluster:
  name: ${EKS_CLUSTER_NAME}

controller:
  replicaCount: 3
  resources:
    requests:
      cpu: 1000m
      memory: 4Gi
  persistence:
    storageClass: gp2
    size: 100Gi
  tolerations:
    - key: group
      value: pinot
      operator: Equal
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: alpha.eksctl.io/nodegroup-name
                operator: In
                values:
                  - pinot      
  external:
    enabled: false
  data:
    dir: ${S3_BUCKET_URI}
  extra:
    configs: |-
        pinot.set.instance.id.to.hostname=true
        controller.task.scheduler.enabled=true
        controller.local.temp.dir=/tmp/pinot-tmp-data/
        controller.enable.split.commit=true
        pinot.controller.storage.factory.class.s3=org.apache.pinot.plugin.filesystem.S3PinotFS
        pinot.controller.storage.factory.s3.region=${EKS_CLUSTER_REGION}
        pinot.controller.segment.fetcher.protocols=file,http,s3
        pinot.controller.segment.fetcher.s3.class=org.apache.pinot.common.utils.fetcher.PinotFSSegmentFetcher
        pinot.controller.segment.commit.timeout=300000  # 5 minutes
        pinot.controller.segment.completion.retry.interval=60000  # 1 minute

broker:
  probes:
    livenessEnabled: true
  replicaCount: 3
  resources:
    requests:
      cpu: 1000m
      memory: 4Gi
  tolerations:
    - key: group
      value: pinot
      operator: Equal
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: alpha.eksctl.io/nodegroup-name
                operator: In
                values:
                  - pinot                              
  external:
    enabled: false

server:
  probes:
    livenessEnabled: true
    liveness:
      timeoutSeconds: 120
  replicaCount: 3
  resources:
    requests:
      cpu: 1000m
      memory: 4Gi
  persistence:
    storageClass: gp2
    size: 200Gi   
  jvmOpts: "-Xms512M -Xmx4G -XX:+UseG1GC  -XX:GCLockerInvocationsThreshold=10 -XX:MaxGCPauseMillis=200 -Xlog:gc*:file=/opt/pinot/gc-pinot-server.log"  
  tolerations:
    - key: group
      operator: Equal
      value: pinot
      effect: NoSchedule
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: alpha.eksctl.io/nodegroup-name
                operator: In
                values:
                  - pinot                   
  extra:
    configs: |-
        pinot.set.instance.id.to.hostname=true
        pinot.server.instance.realtime.alloc.offheap=true
        pinot.query.server.port=7321
        pinot.query.runner.port=7732
        pinot.server.instance.enable.split.commit=true
        pinot.server.storage.factory.class.s3=org.apache.pinot.plugin.filesystem.S3PinotFS
        pinot.server.storage.factory.s3.region=${EKS_CLUSTER_REGION}
        pinot.server.storage.factory.s3.httpclient.maxConnections=50
        pinot.server.storage.factory.s3.httpclient.socketTimeout=30s
        pinot.server.storage.factory.s3.httpclient.connectionTimeout=2s
        pinot.server.storage.factory.s3.httpclient.connectionTimeToLive=0s
        pinot.server.storage.factory.s3.httpclient.connectionAcquisitionTimeout=10s
        pinot.server.segment.fetcher.protocols=file,http,s3
        pinot.server.segment.fetcher.s3.class=org.apache.pinot.common.utils.fetcher.PinotFSSegmentFetcher
        pinot.offheap.buffer.factory=org.apache.pinot.segment.spi.memory.unsafe.UnsafePinotBufferFactory
        pinot.server.instance.realtime.segment.completion.max.duration=300000  # 5 minutes
        pinot.server.instance.realtime.segment.completion.retry.interval=60000  # 1 minute
        pinot.server.instance.kafka.fetch.offset.timeout=15000  # 15 seconds for offset fetch
        pinot.server.instance.kafka.connection.timeout=30000  # 30 seconds for connection timeout
        pinot.server.instance.segment.loader.timeout=300000  # 5 minutes

minion:
  persistence:
    storageClass: gp2
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: alpha.eksctl.io/nodegroup-name
                operator: In
                values:
                  - workers
  extra:
    configs: |-
        pinot.set.instance.id.to.hostname=true
        pinot.minion.storage.factory.class.s3=org.apache.pinot.plugin.filesystem.S3PinotFS
        pinot.minion.storage.factory.s3.region=${EKS_CLUSTER_REGION}
        pinot.minion.segment.fetcher.protocols=file,http,s3
        pinot.minion.segment.fetcher.s3.class=org.apache.pinot.common.utils.fetcher.PinotFSSegmentFetcher

minionStateless:
  persistence:
    storageClass: gp2
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: alpha.eksctl.io/nodegroup-name
                operator: In
                values:
                  - workers

zookeeper:
  replicaCount: 3
  resources:
    requests:
      cpu: 1
      memory: 2Gi
  tolerations:
    - key: group
      value: zookeeper
      effect: NoSchedule
  persistence:
    storageClass: gp2
    size: 10Gi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: alpha.eksctl.io/nodegroup-name
                operator: In
                values:
                  - zookeeper
