apiVersion: v1
kind: Service
metadata:
  name: zookeeper-admin-service
  labels:
    app: zookeeper
    component: admin
spec:
  selector:
    app: zookeeper
    component: admin
  ports:
    - name: admin
      protocol: TCP
      port: 8080
      targetPort: 8080
